app = 'emma-kong-uezrhw'
primary_region = 'lhr'

[build]

# Added from tutorial
# Kong Gateway
[[services]]
  internal_port = 8000
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
