# fly.toml app configuration file generated for emma-kong-uezrhw on 2024-10-31T20:30:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'emma-kong-uezrhw'
primary_region = 'ewr'

[build]

# Added from tutorial
# Kong Gateway
[[services]]
  internal_port = 8000
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

# Kong Admin API
[[services]]
  internal_port = 8001
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8001

# Additional Kong Admin API on port 8444
[[services]]
  internal_port = 8444
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8444

# Additional Kong Admin UI on port 8002
[[services]]
  internal_port = 8002
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8002

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
